### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by Xchuantangfeng** [Mmx233/BitSrunLoginGo_Openwrt#1]
请问大佬这个插件怎么用啊？在op里面安装了，但是不会使用啊

**Comment by Mmx233** [comment]
用法与[原版](https://github.com/Mmx233/BitSrunLoginGo)相同，只是压缩了程序、添加了开机启动，并指定了配置文件而已

**Comment by Xchuantangfeng** [comment]
> 大佬可以留一下联系方式吗，想具体请教一下，实在是不太会用，今天下午搞了一下午，害

**Comment by Xchuantangfeng** [comment]
大佬可以留一下联系方式吗，想具体请教一下，实在是不太会用，今天下午搞了一下午，害

**Comment by Mmx233** [comment]
telegram https://t.me/Mmx2468 mail admin@mmxblog.com
