### ISSUE TITLE
救救！ipk编译成功了，但是开机总是不能自动启动

### ISSUE THREAD

**Issue by benyuan2333** [Mmx233/BitSrunLoginGo_Openwrt#4]
加×权限都给了，手动点启动项里面的启动能启动，启动项顺序99。大佬能帮忙看一下怎么弄嘛，你的tg我加不进去

**Comment by Mmx233** [comment]
请打开debug模式，并提供日志文件内容截图

**Comment by benyuan2333** [comment]
下午我把光猫的光纤线拔了重新插好像是能自动登录，就是不知道为什么开机启动不了
![image](https://user-images.githubusercontent.com/72808452/156794064-0501acbc-b5bd-455d-ab42-08dbecc265ee.png)
![image](https://user-images.githubusercontent.com/72808452/156794940-b9b2159c-0547-4932-93c2-01272da01bf9.png)

**Comment by Mmx233** [comment]
请尝试调高timeout，比如30秒

**Comment by Mmx233** [comment]
或者直接使用守护模式

**Comment by benyuan2333** [comment]
感谢大佬，我在init.d里面的脚本start语句里面添加了守护进程也设置了30s的timeout，已经可以开机自启了

**Comment by Mmx233** [comment]
虽然但是，我指的是`settings`->`guardian`
